services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: employees
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .                
      dockerfile: EmployeeManager.Api/Dockerfile  
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=db;Database=employees;Username=app;Password=app"
      Jwt__Key: ${JWT__KEY}     
      Jwt__Issuer: "EmployeeManager"
      Jwt__Audience: "EmployeeManagerUsers"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"

volumes:
  db_data:
